TILE_SIZE = 32
VERTICAL_TILE_NUM = 26
HORIZONTAL_TILE_NUM = 20

WIDTH = HORIZONTAL_TILE_NUM * TILE_SIZE
HEIGHT = VERTICAL_TILE_NUM * TILE_SIZE

SCREEN_WIDTH = WIDTH * 2
SCREEN_HEIGHT = HEIGHT
FPS =  60
BACKGROUND_COL = (0, 0, 0)